### ISSUE TITLE
Unecessary object-function comination

### ISSUE THREAD

**Issue by Razpudding** [DaveBitter/minor-webdev_web-app-from-scratch#18]
So you create a render object which has a all function which calls renderAll?
Wy not just have renderAll be part of the render object?

`var render = {
        all: function (data) {
            renderAll(data);
        },
        detail: function (data) {
            renderDetail(data);
        }
    }`

**Comment by DaveBitter** [comment]
You're right, seems redundant

**Comment by DaveBitter** [comment]
Wait, what? This is how we did it on the first day of WAFS right? When I make it like this `var render = { all: renderAll(data), detail: function (data) { renderDetail(data); } }` it gives an error that renderAll is not a function
