### ISSUE TITLE
Please explain how the pattern you made for the SPA assignment works

### ISSUE THREAD

**Issue by Razpudding** [DaveBitter/minor-webdev_web-app-from-scratch#7]
https://github.com/DaveBitter/minor-webdev_web-app-from-scratch/blob/master/exercise_5/static/js/app.js

Maybe you can show the class how this works? It looks like an interesting pattern.

**Comment by DaveBitter** [comment]
Sure! I build the most basic task that the script should do. Whenever the hash changes, get all sections and check if the section.id equals the hash. If so, add active, if not remove active. Small addition, add active to the link with this has as a href.
